### PR TITLE
BugFix: Show more then one/first sources in popup.

### PR DESCRIPTION
**Pull request by nice-redbull**
BugFix: Show more then one/first sources in popup.

### CODE REVIEW

**Comment by lingej** [comment]
What do you want to achive?

BR Joerg

**Comment by lingej** [comment]
$this->source is already set in controller/system.php which extends popup controller

**Comment by nice-redbull** [comment]
I would like to be "popup" showed several graphs in contrast only one.

function "buildDataStruct ($ this-> host, $ this-> service, $ this-> view, $ this-> source);"
uses "Null"  as an indicator that you need to show not only one / first graffika.
and therefore need to "sourse" pass Null.

**Comment by lingej** [comment]
https://github.com/lingej/pnp4nagios/blob/master/share/pnp/application/controllers/system.php#L32

$this->source is Null if not set

**Comment by nice-redbull** [comment]
o. ok. thx

**Pull request closed without merging**
